// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"fmt"
)

// DpuExtensionServiceLifecycleState Exact durable Core reconciliation state for DPF Helm chart services
type DpuExtensionServiceLifecycleState string

// List of DpuExtensionServiceLifecycleState
const (
	DPUEXTENSIONSERVICELIFECYCLESTATE_CREATING DpuExtensionServiceLifecycleState = "Creating"
	DPUEXTENSIONSERVICELIFECYCLESTATE_READY    DpuExtensionServiceLifecycleState = "Ready"
	DPUEXTENSIONSERVICELIFECYCLESTATE_UPDATING DpuExtensionServiceLifecycleState = "Updating"
	DPUEXTENSIONSERVICELIFECYCLESTATE_DELETING DpuExtensionServiceLifecycleState = "Deleting"
	DPUEXTENSIONSERVICELIFECYCLESTATE_DELETED  DpuExtensionServiceLifecycleState = "Deleted"
	DPUEXTENSIONSERVICELIFECYCLESTATE_FAILED   DpuExtensionServiceLifecycleState = "Failed"
)

// All allowed values of DpuExtensionServiceLifecycleState enum
var AllowedDpuExtensionServiceLifecycleStateEnumValues = []DpuExtensionServiceLifecycleState{
	"Creating",
	"Ready",
	"Updating",
	"Deleting",
	"Deleted",
	"Failed",
}

func (v *DpuExtensionServiceLifecycleState) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DpuExtensionServiceLifecycleState(value)
	for _, existing := range AllowedDpuExtensionServiceLifecycleStateEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DpuExtensionServiceLifecycleState", value)
}

// NewDpuExtensionServiceLifecycleStateFromValue returns a pointer to a valid DpuExtensionServiceLifecycleState
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDpuExtensionServiceLifecycleStateFromValue(v string) (*DpuExtensionServiceLifecycleState, error) {
	ev := DpuExtensionServiceLifecycleState(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DpuExtensionServiceLifecycleState: valid values are %v", v, AllowedDpuExtensionServiceLifecycleStateEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DpuExtensionServiceLifecycleState) IsValid() bool {
	for _, existing := range AllowedDpuExtensionServiceLifecycleStateEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DpuExtensionServiceLifecycleState value
func (v DpuExtensionServiceLifecycleState) Ptr() *DpuExtensionServiceLifecycleState {
	return &v
}

type NullableDpuExtensionServiceLifecycleState struct {
	value *DpuExtensionServiceLifecycleState
	isSet bool
}

func (v NullableDpuExtensionServiceLifecycleState) Get() *DpuExtensionServiceLifecycleState {
	return v.value
}

func (v *NullableDpuExtensionServiceLifecycleState) Set(val *DpuExtensionServiceLifecycleState) {
	v.value = val
	v.isSet = true
}

func (v NullableDpuExtensionServiceLifecycleState) IsSet() bool {
	return v.isSet
}

func (v *NullableDpuExtensionServiceLifecycleState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDpuExtensionServiceLifecycleState(val *DpuExtensionServiceLifecycleState) *NullableDpuExtensionServiceLifecycleState {
	return &NullableDpuExtensionServiceLifecycleState{value: val, isSet: true}
}

func (v NullableDpuExtensionServiceLifecycleState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDpuExtensionServiceLifecycleState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
